In [7]:
import pandas as pd

In [8]:
ev=pd.read_csv('EVcharging.csv')
ev

,Station ID,Latitude,Longitude,Address,Charger Type,Cost (USD/kWh),Availability,Distance to City (km),Usage Stats (avg users/day),Station Operator,Charging Capacity (kW),Connector Types,Installation Year,Renewable Energy Source,Reviews (Rating),Parking Spots,Maintenance Frequency
0,EVS00001,-33.400998,77.974972,"4826 Random Rd, City 98, Country",AC Level 2,0.27,9:00-18:00,4.95,35,EVgo,350,"CCS, CHAdeMO",2013,Yes,4.0,7,Annually
1,EVS00002,37.861857,-122.490299,"8970 San Francisco Ave, San Francisco",DC Fast Charger,0.19,24-Jul,4.96,83,EVgo,350,"Tesla, Type 2",2010,Yes,3.9,2,Monthly
2,EVS00003,13.776092,100.412776,"5974 Bangkok Ave, Bangkok",AC Level 2,0.48,6:00-22:00,8.54,24,ChargePoint,50,"Type 2, CCS",2019,No,3.6,9,Annually
3,EVS00004,43.628250,-79.468935,"6995 Toronto Ave, Toronto",AC Level 1,0.41,9:00-18:00,13.28,70,Greenlots,350,Type 2,2010,Yes,4.2,7,Monthly
4,EVS00005,19.119865,72.913368,"5704 Mumbai Ave, Mumbai",AC Level 2,0.11,9:00-18:00,9.76,19,EVgo,350,CCS,2015,Yes,3.7,6,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,EVS04996,52.406921,13.441112,"614 Berlin Ave, Berlin",DC Fast Charger,0.31,9:00-18:00,6.05,67,Ionity,50,CCS,2014,Yes,3.4,3,Monthly
4996,EVS04997,-23.503534,-46.535017,"5494 São Paulo Ave, São Paulo",AC Level 1,0.22,24-Jul,16.92,68,Tesla,350,CCS,2010,Yes,4.6,10,Quarterly
4997,EVS04998,41.882499,-87.662551,"7567 Chicago Ave, Chicago",DC Fast Charger,0.20,6:00-22:00,13.27,89,ChargePoint,150,CHAdeMO,2015,Yes,3.6,3,Monthly
4998,EVS04999,25.398405,55.295233,"8710 Dubai Ave, Dubai",DC Fast Charger,0.19,9:00-18:00,4.03,44,ChargePoint,150,"CCS, CHAdeMO",2016,Yes,4.7,3,Quarterly
4999,EVS05000,34.093017,-118.207567,"1221 Los Angeles Ave, Los Angeles",AC Level 2,0.35,24-Jul,1.12,15,EVgo,50,"CHAdeMO, Type 2",2023,No,3.7,6,Quarterly

In [11]:
ev.columns

Index(['Station ID', 'Latitude', 'Longitude', 'Address', 'Charger Type',
       'Cost (USD/kWh)', 'Availability', 'Distance to City (km)',
       'Usage Stats (avg users/day)', 'Station Operator',
       'Charging Capacity (kW)', 'Connector Types', 'Installation Year',
       'Renewable Energy Source', 'Reviews (Rating)', 'Parking Spots',
       'Maintenance Frequency'],
      dtype='object')

In [12]:
ev = ev.rename(columns={
    'Usage Stats (avg users/day)': 'demand',
    'Charging Capacity (kW)': 'capacity',
    'Cost (USD/kWh)': 'cost',
    'Distance to City (km)': 'distance'
})

In [13]:
ev

,Station ID,Latitude,Longitude,Address,Charger Type,cost,Availability,distance,demand,Station Operator,capacity,Connector Types,Installation Year,Renewable Energy Source,Reviews (Rating),Parking Spots,Maintenance Frequency
0,EVS00001,-33.400998,77.974972,"4826 Random Rd, City 98, Country",AC Level 2,0.27,9:00-18:00,4.95,35,EVgo,350,"CCS, CHAdeMO",2013,Yes,4.0,7,Annually
1,EVS00002,37.861857,-122.490299,"8970 San Francisco Ave, San Francisco",DC Fast Charger,0.19,24-Jul,4.96,83,EVgo,350,"Tesla, Type 2",2010,Yes,3.9,2,Monthly
2,EVS00003,13.776092,100.412776,"5974 Bangkok Ave, Bangkok",AC Level 2,0.48,6:00-22:00,8.54,24,ChargePoint,50,"Type 2, CCS",2019,No,3.6,9,Annually
3,EVS00004,43.628250,-79.468935,"6995 Toronto Ave, Toronto",AC Level 1,0.41,9:00-18:00,13.28,70,Greenlots,350,Type 2,2010,Yes,4.2,7,Monthly
4,EVS00005,19.119865,72.913368,"5704 Mumbai Ave, Mumbai",AC Level 2,0.11,9:00-18:00,9.76,19,EVgo,350,CCS,2015,Yes,3.7,6,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,EVS04996,52.406921,13.441112,"614 Berlin Ave, Berlin",DC Fast Charger,0.31,9:00-18:00,6.05,67,Ionity,50,CCS,2014,Yes,3.4,3,Monthly
4996,EVS04997,-23.503534,-46.535017,"5494 São Paulo Ave, São Paulo",AC Level 1,0.22,24-Jul,16.92,68,Tesla,350,CCS,2010,Yes,4.6,10,Quarterly
4997,EVS04998,41.882499,-87.662551,"7567 Chicago Ave, Chicago",DC Fast Charger,0.20,6:00-22:00,13.27,89,ChargePoint,150,CHAdeMO,2015,Yes,3.6,3,Monthly
4998,EVS04999,25.398405,55.295233,"8710 Dubai Ave, Dubai",DC Fast Charger,0.19,9:00-18:00,4.03,44,ChargePoint,150,"CCS, CHAdeMO",2016,Yes,4.7,3,Quarterly
4999,EVS05000,34.093017,-118.207567,"1221 Los Angeles Ave, Los Angeles",AC Level 2,0.35,24-Jul,1.12,15,EVgo,50,"CHAdeMO, Type 2",2023,No,3.7,6,Quarterly

In [14]:
X = ev[['capacity','cost','distance','Parking Spots','Reviews (Rating)']]
y = ev['demand']

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [16]:
y_pred = model.predict(X_test)

In [17]:
y_pred

array([53.47105025, 52.70822177, 55.70134931, 58.83941063, 55.05852634,
       53.04941744, 52.33878283, 55.34274447, 57.7037209 , 54.93655952,
       55.73406458, 56.99198188, 52.66921775, 56.3783659 , 55.04975796,
       52.74432072, 58.19541463, 56.59881503, 57.48841269, 57.71974623,
       53.2614325 , 55.35880654, 55.23214368, 58.58262207, 55.58454049,
       56.49634343, 54.67634171, 55.34359522, 55.13765917, 57.37162067,
       58.45369317, 57.24208681, 53.11883135, 55.58005426, 54.0104903 ,
       55.72226332, 55.80759863, 55.57325964, 58.31519617, 52.79869663,
       55.41042512, 53.52565373, 56.27022266, 55.52972717, 54.60926042,
       57.17421393, 53.17388884, 55.221285  , 55.88217775, 56.4281953 ,
       54.62190193, 56.94751058, 55.4681093 , 55.67412636, 54.96029137,
       55.63115748, 54.51315385, 58.12406363, 56.26825361, 58.3148096 ,
       55.8382527 , 54.68897363, 55.30749988, 57.70498291, 56.70473882,
       56.45350675, 54.88859435, 53.78745522, 55.85969647, 54.49181635,
       57.86193104, 55.65621775, 52.28791583, 55.26781916, 55.1163791 ,
       55.26228554, 54.82213087, 56.66624951, 55.49241433, 56.81924972,
       55.60544202, 52.99128862, 53.33259056, 56.19621593, 55.60140502,
       55.1359881 , 56.40163487, 55.89339086, 56.17770902, 57.03440853,
       56.04598214, 57.47917698, 52.91306143, 58.29419169, 54.63077933,
       53.50945557, 56.98785909, 57.03991413, 55.64129463, 54.13413175,
       55.04699139, 56.54940617, 55.51378548, 54.12575635, 54.34920469,
       55.7274728 , 53.69539263, 55.35728494, 57.96962469, 55.28639136,
       56.17065868, 54.76860485, 54.24679557, 55.69548433, 55.50745715,
       55.44059326, 52.71148519, 55.74665938, 57.04980901, 54.59378016,
       57.08649856, 53.30568835, 55.5973524 , 56.69451348, 58.30993155,
       55.75643218, 58.66055279, 57.52492027, 54.55933579, 57.40344073,
       55.5545171 , 57.51489389, 55.00906376, 55.80392072, 55.92215258,
       53.76824092, 57.31474728, 55.7306417 , 56.67281822, 56.09226154,
       55.102724  , 57.65794985, 54.31796208, 56.52604644, 57.52190316,
       54.04113328, 58.79766182, 57.04707267, 55.91231214, 55.3397782 ,
       53.62574284, 57.11889161, 55.33904706, 55.40040524, 55.53247253,
       56.37200911, 54.99125646, 56.61235496, 54.64461239, 55.55547084,
       56.32537103, 57.50710717, 55.39049548, 56.86059234, 57.38176997,
       54.69417924, 57.01241272, 56.46950895, 58.86421045, 54.07138367,
       58.00709505, 55.2004977 , 55.70531658, 54.20567947, 54.20519295,
       56.58649123, 55.9823188 , 54.56103725, 55.24312947, 55.90258279,
       56.17595056, 55.40713846, 55.65379929, 56.78569331, 56.78602175,
       54.60615503, 53.683731  , 57.23748175, 55.25127908, 57.10605735,
       53.05814172, 54.32577171, 55.8614991 , 53.80370317, 55.04779533,
       53.30423383, 57.72507108, 54.76507681, 56.02007976, 56.57904759,
       56.97214936, 56.1655728 , 57.59918987, 58.62119232, 57.97407675,
       54.65831408, 56.9759658 , 55.95459105, 57.2089154 , 54.4049373 ,
       53.97976221, 56.67979509, 55.39115557, 55.69835792, 55.13469815,
       55.43282807, 52.01866796, 54.13005553, 55.84341237, 56.67242806,
       57.20626374, 55.86880356, 54.0094004 , 54.15863462, 57.49950945,
       56.10802973, 54.32529975, 56.51254625, 52.69637771, 55.29486854,
       56.47058059, 56.30028006, 56.79730788, 55.60996095, 55.05940058,
       56.06429927, 56.5229695 , 55.75848223, 56.38060827, 58.0644776 ,
       54.91849477, 54.09737568, 53.653153  , 56.75588343, 54.07339129,
       58.53572211, 55.54113167, 54.94650596, 57.52788665, 56.2850623 ,
       55.55027855, 57.0906299 , 55.73667275, 58.38865311, 54.66385582,
       55.60674379, 54.40107267, 55.5222346 , 53.51363186, 57.82535987,
       55.03708155, 56.27845798, 54.56025989, 55.74067114, 55.92767062,
       56.64402752, 54.12603169, 56.50874321, 56.46453242, 55.73409511,
       55.49787968, 56.46116028, 54.94276356, 54.95114081, 55.71210386,
       55.50217669, 57.46129314, 55.10939144, 54.43371106, 59.14751609,
       56.56150659, 55.28782078, 56.4348176 , 54.59115332, 55.32716028,
       54.94692053, 55.81792772, 55.10086313, 57.70022592, 54.83250826,
       55.38362438, 56.15633821, 56.5792539 , 57.31297285, 59.07113636,
       56.72758804, 57.13714904, 55.54878851, 55.59426744, 54.46945152,
       57.96807202, 55.01524324, 54.56370661, 54.0123922 , 54.60632137,
       52.54813532, 54.0763209 , 56.21073185, 56.0206728 , 56.7277665 ,
       55.44048717, 54.96444703, 54.10340368, 58.44815111, 55.95719858,
       55.09435398, 52.92577646, 54.98802838, 54.28587243, 56.78998528,
       54.09324984, 58.15835719, 57.24828887, 56.23716091, 54.57405501,
       56.94834456, 56.27805405, 55.57852157, 56.33486882, 56.08434774,
       55.38384074, 54.55152581, 57.02088241, 54.10796077, 57.773236  ,
       55.00687638, 56.51293109, 57.3684559 , 55.92897393, 56.91403676,
       55.99809873, 54.13834346, 54.82030679, 59.17402522, 55.05630943,
       56.55063701, 54.79213507, 55.27742538, 55.21357579, 57.7692969 ,
       56.31834216, 57.32235255, 55.79538774, 55.34666573, 55.61410326,
       55.82693362, 56.65478433, 55.70487368, 57.44449377, 57.96351179,
       53.87604237, 54.26244187, 53.304289  , 57.37005055, 56.08584734,
       55.63317225, 55.52049645, 53.96091314, 57.32131908, 56.76034203,
       53.0367351 , 56.58969131, 57.06850273, 55.76561873, 52.18388723,
       57.47793933, 56.69991669, 57.31409203, 54.68672068, 54.60315482,
       53.04449064, 56.66159074, 55.7609377 , 58.45920814, 52.37992153,
       55.52996467, 53.3026396 , 55.06272248, 54.4871763 , 56.74273939,
       57.99929524, 54.42452733, 56.62514248, 55.0199945 , 57.48534322,
       56.50122044, 54.8309268 , 55.75239581, 55.31820964, 57.45152996,
       55.18647489, 55.03854276, 53.31131147, 56.57153129, 55.9530154 ,
       53.18422287, 56.10051372, 54.01145037, 55.48766141, 55.98050743,
       55.87095457, 55.86589481, 54.84903924, 58.80747697, 55.48774712,
       56.64008658, 52.17965503, 56.09234682, 56.03015875, 54.7032808 ,
       55.68917915, 57.89389043, 54.51785014, 56.76709452, 56.0526467 ,
       54.74105774, 54.52166794, 54.58766523, 56.97021846, 55.17618648,
       56.36173327, 55.08507244, 52.6886318 , 54.58431296, 55.40793719,
       54.30452137, 56.46954189, 58.81328263, 56.60071696, 56.28833456,
       55.5165501 , 55.3814311 , 56.13330224, 56.26054537, 57.74709299,
       56.26580222, 56.54568578, 56.79194801, 56.52103377, 54.74614205,
       54.82091546, 57.15612485, 56.42361001, 57.61513615, 55.91154338,
       56.65328194, 53.81722506, 57.12458957, 55.32821618, 56.21073924,
       52.88962683, 55.51152234, 53.77685533, 55.94337586, 56.76868466,
       53.47975273, 57.32812656, 56.25050951, 54.93929517, 56.86606693,
       59.27657328, 55.06968269, 54.61770849, 57.01770233, 56.3878117 ,
       55.49954223, 54.53756844, 54.55183632, 57.02183599, 55.89270323,
       56.53111949, 56.95849914, 56.93251354, 54.06989203, 56.77669482,
       54.34254047, 57.03978425, 54.73763334, 52.45693116, 55.94535727,
       54.14550766, 57.69479932, 54.76984763, 56.99857231, 54.38462911,
       55.9236748 , 52.3876011 , 56.65913702, 54.48335364, 56.7572589 ,
       55.53929233, 55.48207772, 52.95151682, 54.02798143, 54.49856725,
       55.46530039, 54.88149236, 57.95145893, 54.2344162 , 55.48749674,
       54.53724234, 54.08346387, 55.04288674, 57.06074614, 53.67533717,
       53.81356313, 56.01244212, 57.24674244, 53.35267754, 57.27032025,
       54.83482135, 53.6676775 , 55.124419  , 53.66434155, 53.05200467,
       53.55482652, 57.96831915, 53.88335301, 56.51325332, 57.31331927,
       55.575124  , 53.18850083, 58.21080627, 53.58932485, 57.90656634,
       57.15666276, 55.88358343, 56.23418646, 55.70418142, 55.10614036,
       55.32811072, 54.26185968, 55.30987828, 54.82863251, 56.15746589,
       54.45398929, 56.34796789, 53.31001043, 57.90718239, 55.62008474,
       54.6879428 , 55.654852  , 56.46602888, 56.8580628 , 56.35703322,
       55.54700797, 54.96557642, 55.46417799, 54.91128564, 54.65579009,
       55.68946057, 56.99141753, 56.89767284, 53.26880699, 57.03556554,
       55.68384256, 52.62405724, 57.37444877, 56.43022086, 56.14769719,
       55.22356468, 57.87111686, 55.47945214, 56.13274829, 57.19540644,
       55.06850767, 54.21230828, 56.10997879, 55.71792929, 55.49720651,
       55.00896105, 56.24242415, 57.18520345, 55.21834188, 58.23236444,
       54.68425532, 55.64549669, 54.52963705, 56.19375692, 57.1713814 ,
       57.55017901, 56.45774368, 56.1239035 , 54.86121938, 55.47663896,
       53.1393744 , 57.04912749, 56.77218776, 56.65990375, 55.15333671,
       54.26894778, 55.75779131, 56.78259856, 52.97609448, 53.6723824 ,
       54.25825016, 57.63210196, 54.65870362, 56.66430575, 54.1736567 ,
       54.93976092, 54.60926066, 57.63138434, 58.25920391, 55.7675657 ,
       57.85728786, 57.25772777, 54.57662939, 56.29663437, 54.82267398,
       56.32902523, 57.61086357, 56.27075039, 53.50497921, 58.89624069,
       55.94787118, 57.97578114, 56.10060262, 53.60999457, 54.00587956,
       53.6828695 , 58.10900656, 56.12677809, 57.41184461, 55.18823503,
       56.5743933 , 56.26854228, 58.48338853, 58.11514165, 55.80356803,
       56.37733603, 56.24086088, 53.99655968, 55.58568433, 55.39932166,
       54.08955307, 56.91079372, 55.34698558, 52.89206497, 55.42576956,
       56.46691384, 54.27191312, 57.0781892 , 57.82648551, 55.18041941,
       56.60712361, 55.90645343, 53.94483082, 54.86372764, 52.52863734,
       55.3293217 , 55.24406474, 56.5226569 , 56.22849033, 56.43497272,
       56.48406879, 55.938159  , 57.42566485, 56.08250939, 56.21233553,
       53.47226631, 56.46481418, 55.88979619, 55.58779325, 56.69784638,
       54.70654038, 54.62890384, 54.61862053, 56.11910495, 58.5156066 ,
       58.55592892, 56.69666505, 53.68046036, 53.10926512, 57.36819293,
       56.34252436, 56.51700039, 56.53980773, 54.83336126, 53.79257759,
       54.45297875, 55.22555592, 57.74688014, 54.60752862, 57.34366332,
       54.13322691, 53.86804344, 55.07958675, 54.76027497, 54.37929018,
       57.22517461, 54.407422  , 55.36030621, 54.53094606, 54.33013097,
       54.60175921, 54.44345182, 54.40117612, 54.97544008, 54.87289384,
       55.92144743, 54.47910313, 54.64729784, 54.97301455, 53.18293613,
       57.78453651, 54.84872848, 53.19125271, 57.17659868, 57.85997708,
       54.97321495, 54.73555271, 57.24244376, 53.77000252, 56.56766152,
       55.72107923, 53.81635804, 55.76710404, 52.84969509, 55.55488643,
       54.85823875, 54.3345732 , 56.40890126, 54.38723503, 55.23798871,
       55.90381843, 53.92639469, 55.11650352, 56.37963302, 58.32293864,
       55.73141726, 54.10911885, 55.80786241, 56.18672361, 54.29765142,
       54.47704308, 55.68729167, 56.1080479 , 55.21346874, 56.25643912,
       56.04646545, 53.62419137, 56.23552276, 53.83778631, 56.08745306,
       55.99081717, 58.50739026, 56.39862958, 56.98143526, 55.6844069 ,
       54.24229071, 57.03641352, 55.08699355, 56.08292374, 57.3035029 ,
       57.80421532, 56.94424524, 56.86322551, 54.99657387, 54.76683295,
       53.80105524, 55.8603211 , 56.6771819 , 56.78140531, 54.50828374,
       55.40796561, 54.4477244 , 55.79247836, 57.1252299 , 53.5077521 ,
       53.93577497, 54.66214684, 53.61849669, 56.37659074, 54.38704301,
       57.40756653, 57.750597  , 56.42504988, 55.41775696, 57.01826618,
       55.02511831, 53.95784193, 56.04929177, 56.83496017, 56.54070099,
       54.23167636, 57.37640499, 55.9860556 , 57.34231736, 54.43363916,
       56.26484367, 56.59607432, 56.68028584, 57.52963934, 57.58845883,
       56.0142667 , 55.8287575 , 55.88366938, 54.23612597, 55.37760502,
       55.4946445 , 53.84598684, 53.60760009, 55.28748319, 54.76499194,
       55.93181404, 56.23705887, 55.56944746, 53.79142443, 56.69120601,
       54.86449156, 55.18560404, 58.04992787, 56.43783632, 57.38681003,
       55.45370269, 55.73689004, 53.00949182, 55.78026476, 55.96529278,
       56.90509376, 55.45571955, 57.59323457, 54.9989773 , 55.05394678,
       56.74276989, 55.93048851, 56.8927592 , 53.95536018, 57.21147176,
       53.3944518 , 54.74839953, 55.59932141, 57.64712452, 56.4069245 ,
       55.29003616, 55.06569293, 57.24748613, 56.48945847, 55.30673988,
       54.14765151, 54.77677426, 55.48300167, 53.71005923, 55.2001353 ,
       54.99828993, 56.59703922, 56.20307389, 56.82295484, 52.23495535,
       55.96446927, 57.88673946, 55.12780968, 56.61516662, 55.07229916,
       55.78234934, 54.77351621, 58.23929886, 54.9964048 , 57.87020738,
       53.34888622, 55.69063538, 55.30485064, 56.37623889, 55.2018144 ,
       54.84940641, 55.80321252, 56.93652991, 56.3701276 , 54.27661104,
       55.43535763, 54.46835164, 55.96810939, 55.06733129, 53.01724023,
       55.13666554, 56.46951056, 54.81481676, 57.3503383 , 55.16155015,
       56.08878717, 54.09531073, 52.93886347, 54.89007121, 53.55135659,
       59.04385391, 54.75264484, 57.1955131 , 57.40496141, 55.16820015,
       55.47744404, 54.48440954, 54.41013615, 53.00595499, 52.93477922,
       56.41150268, 54.1309108 , 54.24012918, 53.73207867, 54.08474199,
       55.31825066, 52.95542244, 57.46359681, 55.96447568, 57.2129728 ,
       57.12946777, 56.30631804, 54.80146574, 56.1302779 , 57.13189699,
       53.63216346, 57.57997665, 54.27814516, 57.08797439, 56.04674649,
       57.76558833, 52.05573098, 54.33894776, 53.75489456, 56.0285901 ,
       55.19998116, 54.87754091, 55.64603707, 54.88491421, 55.57510174,
       56.8813128 , 56.3308396 , 57.06833406, 55.24716344, 53.51675457,
       57.8023562 , 56.29951691, 56.74912472, 56.00140538, 56.70871535,
       57.15909302, 56.00062572, 54.67165641, 56.08717649, 55.93469001,
       54.81943206, 55.12451529, 56.66711194, 52.87543998, 55.49335915,
       53.9734519 , 55.50850228, 54.11158301, 53.29782012, 53.35942858,
       52.90549004, 58.08003931, 53.26995301, 55.17107599, 56.46760348,
       56.04794511, 56.15589642, 52.82413884, 54.04596434, 55.61229009,
       52.87946961, 56.51402954, 55.58233841, 53.6836379 , 54.68748359,
       54.31413166, 55.98050678, 58.2341461 , 55.78941719, 57.54231952,
       57.26656934, 55.04869243, 57.03298153, 56.5338036 , 55.61467642,
       53.69277008, 53.66011247, 56.48079965, 56.14393432, 54.19797814,
       54.4537577 , 55.911567  , 55.24779451, 55.63646443, 55.02199031,
       54.02262316, 54.69486453, 55.37220241, 56.48116911, 55.10514649])

In [19]:
ev['predicted_demand'] = model.predict(X)

In [20]:
ev['predicted_demand']

0       54.737633
1       55.605442
2       53.622001
3       54.467078
4       55.940912
          ...
4995    54.965467
4996    56.529647
4997    56.234598
4998    57.305550
4999    54.537242
Name: predicted_demand, Length: 5000, dtype: float64

In [21]:
ev.to_csv("ev_output.csv", index=False)